heat_template_version: 2016-04-08

description: >
  Helps to understand the parameter section with custom constraints. First run
  this template 'openstack stack create --dry-run ' and see what error it
  reports. Then fix it with using --parameter flavor=m1.small.
  You could try to use invalide flavor and see that constraint is verifying
  the given flavor :)
  Also try with default value as commented below

parameters:
# Try to use flavor parameter and validate it with custom constraints
# glance.image
  flavor:
    type: string
    description: Flavor to use for the WordPress server.
    constraints:
      - custom_constraint: nova.flavor
#   Also, try to uncomment below line, to use the default value, in that case,
# user is not required to give --parameter.
#    default: m1.small