heat_template_version: 2016-04-08

description: >
  Uses provider template and helps to learn about custom typing
  Try to create stack and check the resource_type for 'rsc' resource by
  doing 'openstack stack resource list <stack name>. Heat creates the
  custom type as internal stack.

resources:
  rsc:
    type: 7-provider-template.yaml
    properties:
      param1: "1234"
outputs:
  echo_str:
    value:
      get_attr: [rsc, echo_str]
